services:

  postgres:
    image: postgres:16-alpine
    container_name: postgres-bjjmarket
    environment:
      POSTGRES_DB: bjjmarket
      POSTGRES_USER: bjjmarket
      POSTGRES_PASSWORD: BjjMarket2026!
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bjjmarket -d bjjmarket"]
      interval: 10s
      timeout: 5s
      retries: 10
  liquibase:
    image: liquibase/liquibase:5.0.1
    container_name: liquibase-container

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./backend/src/main/resources/liquibase:/workspace/

    command: >
      --defaultsFile=/workspace/liquibase.properties
      --searchPath=/workspace
      update

    networks:
      - db-network
    restart: "no"

  backend:
    build: ./backend
    container_name: backend-BJJMarket
    depends_on:
      liquibase:
        condition: service_completed_successfully
    env_file:
      - ./backend/src/main/resources/.env
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - db-network

  frontend-web:
    container_name: frontend-web-BJJMarket
    build:
      context: ./frontend-web
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: "http://10.3.232.162:9090/api"

networks:
  db-network:
    driver: bridge

volumes:
  postgres-data:
