services:

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SqlServer2026"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - sql-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SqlServer2026' -C -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - sql-network
    restart: "no"
    command: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd
      -S sql-server
      -U sa
      -P 'SqlServer2026'
      -C
      -Q \"IF DB_ID('SupermarketDB') IS NULL CREATE DATABASE SupermarketDB\"
      "
  backend:
    build: ./backend
    container_name: backend-BJJMarket
    depends_on:
      db-init:
        condition: service_completed_successfully
    env_file:
      - ./backend/src/main/resources/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - sql-network

  frontend-web:
    container_name: frontend-web-BJJMarket
    build:
      context: ./frontend-web
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"

networks:
  sql-network:
    driver: bridge

volumes:
  sql-data: