services:
  # liquibase:
  #   image: liquibase/liquibase:5.0.1
  #   container_name: liquibase-container-SupermarketDB
  #   volumes:
  #     - ./backend/src/main/resources/liquibase:/workspace/
  #     - ./backend/src/main/resources/liquibase/drivers/mssql-jdbc-13.4.0.jre8.jar:/liquibase/lib/mssql.jar
  #   command: >
  #     --defaultsFile=/workspace/liquibase.properties
  #     --searchPath=/workspace
  #     update
  #   depends_on:
  #     - sql-server
  #   networks:
  #     - sql-network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlServer2026
      - MSSQL_DB=SupermarketDB
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - sql-network

  backend:
    build: ./backend
    container_name: backend-BJJMarket
    env_file:
      - ./backend/src/main/resources/.env
    ports:
      - "8080:8080"
    depends_on:
      - sql-server
    restart: always
    networks:
      - sql-network

  frontend-web:
    container_name: frontend-web-BJJMarket
    build:
      context: ./frontend-web
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  sql-network:
    driver: bridge

volumes:
  sql-data: